# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy.rb"
class Clearctl < Formula
  desc "clearctl CLI tool for authenticating, creating and managing systems"
  homepage "https://clear.ai/"
  version "0.0.1-master-master"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/clear-ai/clearctl/releases/download/v0.0.1-master-master/clearctl_0.0.1-master-master_darwin_amd64.tar.gz", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "a06a0a1c4cd2c1806aea294c45c099af4b4cb80109d176c5608e53627b329869"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/clear-ai/clearctl/releases/download/v0.0.1-master-master/clearctl_0.0.1-master-master_linux_amd64.tar.gz", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6cb2b85c7cb5fe13169d8c0fd96f4241188a7ea85c091927f22873a980ee61c9"
    end
  end
  
  depends_on "awscli"
  depends_on "velero"
  depends_on "kubectl"
  depends_on "terraform"
  depends_on "vault"

  def install
    bin.install "program"
  end
end
