# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy.rb"
class ClearctlCluster < Formula
  desc "clearctl-cluster cluster command only"
  homepage "https://clear.ai/"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/clear-ai/clearctl/releases/download/v0.2.1/clearctl_0.2.1_darwin_amd64.tar.gz", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "27997ac30c0ac6057d09904c5d680713b6c8e50e199591033663ec8d36ba54b8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/clear-ai/clearctl/releases/download/v0.2.1/clearctl_0.2.1_linux_amd64.tar.gz", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9ffc5e0be902277a3b3c874c8b87721f24013efcda0485891d6a239bd3e4b69c"
    end
  end

  def install
    bin.install "clearctl-cluster"
  end
end
